// login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

// partner_create
export const PARTNER_CREATE_START = "PARTNER_CREATE_START";
export const PARTNER_CREATE_SUCCESS = "PARTNER_CREATE_SUCCESS";
export const PARTNER_CREATE_FAIL = "PARTNER_CREATE_FAIL";

// fetch_partner
export const PARTNER_FETCH_START = "PARTNER_FETCH_START";
export const PARTNER_FETCH_SUCCESS = "PARTNER_FETCH_SUCCESS";
export const PARTNER_FETCH_FAIL = "PARTNER_FETCH_FAIL";

// cost_create
export const COST_CREATE_START = "COST_CREATE_START";
export const COST_CREATE_SUCCESS = "COST_CREATE_SUCCESS";
export const COST_CREATE_FAIL = "COST_CREATE_FAIL";

// fetch_cost
export const COST_FETCH_START = "COST_FETCH_START";
export const COST_FETCH_SUCCESS = "COST_FETCH_SUCCESS";
export const COST_FETCH_FAIL = "COST_FETCH_FAIL";

//licenses_create
export const LICENSES_CREATE_START = "LICENSES_CREATE_START";
export const LICENSES_CREATE_SUCCESS = "LICENSES_CREATE_SUCCESS";
export const LICENSES_CREATE_FAIL = "LICENSES_CREATE_FAIL";

// licenses_fetch
export const LICENSES_FETCH_START = "LICENSES_FETCH_START";
export const LICENSES_FETCH_SUCCESS = "LICENSES_FETCH_SUCCESS";
export const LICENSES_FETCH_FAIL = "LICENSES_FETCH_FAIL";

//virus_list
export const VIRUS_FETCH_START = "VIRUS_FETCH_START";
export const VIRUS_FETCH_SUCCESS = "VIRUS_FETCH_SUCCESS";
export const VIRUS_FETCH_FAIL = "VIRUS_FETCH_FAIL";
